name: pos_serabi_kraton
description: POS F&B multi-platform - Serabi Solo Kraton
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  printing: ^5.13.2          # cetak struk PDF (thermal printer)
  pdf: ^3.11.0
  image: ^4.2.0              # encode struk ke JPG
  excel: ^4.0.6              # export laporan ke Excel
  share_plus: ^10.1.2        # share file (JPG/PDF) ke WhatsApp, dll
  cached_network_image: ^3.3.1
  go_router: ^14.2.0         # routing berbasis role
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
